# Site settings
email: info@accept.li
url: http://accept.li
description: "From start-ups, to public sector and large private firms, ACT Consulting will work with you to initialise and support your Testing capabilities. Using our methods and expertise, we will support releasing quality software through your development lifecycle, making each release better every-time"
about_description: "ACT Consulting are independent of large consulting firms, our ambition is to bring expertise and not numbers. As a team we strive to support each other, understanding not only new technologies but existing as well."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/consulting_act
  - title: facebook
    url:
  - title: linkedin
    url: http://linkedin.com
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
